export const ProductsInBulk = [
  {
    title: "Apple AirPods Pro",
    price: "249.99",
    stock: 50,
    description:
      "Apple AirPods Pro offer active noise cancellation, immersive sound, and a customizable fit. With up to 4.5 hours of listening time and a wireless charging case that provides more than 24 hours of battery life, these in-ear headphones are perfect for everyday use.",
    categoryId: "93ae7b89-0e69-420a-aef8-9b34532a9eed",
    brandId: "ee10611c-7282-47fc-a440-633400654cdc",
    variants: [
      { id: 101, variant: "With Wireless Charging Case", price: "0" },
      { id: 102, variant: "With MagSafe Charging Case", price: "20" },
    ],
    cover: "/uploads/image_airpods_pro.png",
    type: "In-Ear",
    noiseCancellation: true,
    batteryLife: "4.5 hours",
    battery: "519",
    wireless: true,
    microphone: true,
    features: "Active Noise Cancellation, Transparency Mode, Adaptive EQ",
    sensor:
      "Dual beamforming microphones, Dual optical sensors, Motion-detecting accelerometer, Speech-detecting accelerometer, Force sensor",
    slug: "apple-airpods-pro",
    colors: [{ id: 201, name: "#FFFFFF" }],
  },
  {
    title: "Samsung Galaxy Buds2",
    price: "149.99",
    stock: 40,
    description:
      "The Samsung Galaxy Buds2 feature active noise cancellation, immersive sound with a compact design, and up to 5 hours of listening time. With the wireless charging case, you can extend the battery life to up to 20 hours.",
    categoryId: "93ae7b89-0e69-420a-aef8-9b34532a9eed",
    brandId: "061ef0bc-8dbc-4691-a884-f1ce8dea17a6",
    variants: [{ id: 103, variant: "Standard Edition", price: "0" }],
    cover: "/uploads/image_galaxy_buds2.png",
    type: "In-Ear",
    noiseCancellation: true,
    batteryLife: "5 hours",
    battery: "472",
    wireless: true,
    microphone: true,
    features: "Active Noise Cancellation, Ambient Sound Mode, Touch Controls",
    sensor:
      "Accelerometer, Gyro Sensor, Proximity Sensor, Hall Sensor, Touch Sensor",
    slug: "samsung-galaxy-buds2",
    colors: [
      { id: 202, name: "#FFFFFF" },
      { id: 203, name: "#000000" },
    ],
  },
  {
    title: "Sony WH-1000XM4",
    price: "349.99",
    stock: 30,
    description:
      "Sony WH-1000XM4 headphones offer industry-leading noise cancellation, premium sound quality, and up to 30 hours of battery life. These over-ear headphones are ideal for travel, work, and relaxation.",
    categoryId: "93ae7b89-0e69-420a-aef8-9b34532a9eed",
    brandId: "c4650b20-1e72-4731-85b7-3987cdc930be",
    variants: [{ id: 104, variant: "Standard Edition", price: "0" }],
    cover: "/uploads/image_sony_wh1000xm4.png",
    type: "Over-Ear",
    noiseCancellation: true,
    batteryLife: "30 hours",
    battery: "1100",
    wireless: true,
    microphone: true,
    features:
      "Industry-Leading Noise Cancellation, Adaptive Sound Control, Touch Sensor Controls",
    sensor: "Proximity Sensor, Wearing Detection, Gesture Sensor",
    slug: "sony-wh-1000xm4",
    colors: [
      { id: 204, name: "#000000" },
      { id: 205, name: "#C0C0C0" },
    ],
  },
  {
    title: "Google Pixel Buds A-Series",
    price: "99.99",
    stock: 60,
    description:
      "Google Pixel Buds A-Series offer rich sound quality, a comfortable fit, and up to 5 hours of listening time. These in-ear headphones are designed for seamless integration with Google Assistant and other Google services.",
    categoryId: "93ae7b89-0e69-420a-aef8-9b34532a9eed",
    brandId: "1d6b0eb8-19fa-4116-b997-bfd4f8aa0955",
    variants: [{ id: 105, variant: "Standard Edition", price: "0" }],
    cover: "/uploads/image_pixel_buds_a_series.png",
    type: "In-Ear",
    noiseCancellation: false,
    batteryLife: "5 hours",
    battery: "550",
    wireless: true,
    microphone: true,
    features:
      "Google Assistant Integration, IPX4 Water Resistance, Touch Controls",
    sensor:
      "Capacitive Touch Sensor, Dual IR Proximity Sensors, Motion Detecting Accelerometer",
    slug: "google-pixel-buds-a-series",
    colors: [
      { id: 206, name: "#FFFFFF" },
      { id: 207, name: "#008080" },
    ],
  },
  {
    title: "Mi Earbuds Basic 2",
    price: "29.99",
    stock: 70,
    description:
      "The Xiaomi Mi True Wireless Earbuds Basic 2 offer great sound quality at an affordable price. With up to 4 hours of battery life on a single charge and a compact charging case that provides up to 12 hours of total playtime, these earbuds are perfect for everyday use.",
    categoryId: "93ae7b89-0e69-420a-aef8-9b34532a9eed",
    brandId: "28f37902-51d3-4734-9994-4edfe3a2e124",
    variants: [{ id: 106, variant: "Standard Edition", price: "0" }],
    cover: "/uploads/image_mi_earbuds_basic2.png",
    type: "In-Ear",
    noiseCancellation: false,
    batteryLife: "4 hours",
    battery: "410",
    wireless: true,
    microphone: true,
    features: "Lightweight Design, Voice Assistant Support, Touch Controls",
    sensor: "Capacitive Touch Sensor, Proximity Sensor",
    slug: "mi-earbuds-basic-2",
    colors: [{ id: 208, name: "#000000" }],
  },
  {
    title: "OnePlus Buds Pro",
    price: "149.99",
    stock: 50,
    description:
      "OnePlus Buds Pro feature smart adaptive noise cancellation, immersive sound quality, and up to 7 hours of listening time on a single charge. With the wireless charging case, you can extend the battery life to up to 38 hours.",
    categoryId: "93ae7b89-0e69-420a-aef8-9b34532a9eed",
    brandId: "23937424-9f80-4b55-a703-cf9dbba82070",
    variants: [{ id: 107, variant: "Standard Edition", price: "0" }],
    cover: "/uploads/image_oneplus_buds_pro.png",
    type: "In-Ear",
    noiseCancellation: true,
    batteryLife: "7 hours",
    battery: "520",
    wireless: true,
    microphone: true,
    features:
      "Smart Adaptive Noise Cancellation, IP55 Water Resistance, Zen Mode Air",
    sensor:
      "Capacitive Touch Sensor, Motion Detecting Accelerometer, Gyroscope, Wear Detection Sensor",
    slug: "oneplus-buds-pro",
    colors: [
      { id: 209, name: "#FFFFFF" },
      { id: 210, name: "#000000" },
    ],
  },
];

// export const ProductsInBulk = [
//   {
//     title: "MacBook Air 2023",
//     price: "1199.99",
//     stock: 20,
//     description:
//       "The MacBook Air 2023 is Apple's latest ultra-thin laptop, featuring a 13.6-inch Liquid Retina display. It is powered by the M2 chip, which provides exceptional performance and power efficiency. With 16GB of unified memory and a 512GB SSD, it handles multitasking and storage with ease. The laptop also offers up to 18 hours of battery life, making it ideal for all-day use.",
//     categoryId: "0f2a83f3-f138-4648-bbab-56c4c322ee85",
//     brandId: "ee10611c-7282-47fc-a440-633400654cdc",
//     variants: [
//       { id: 16, variant: "256GB SSD", price: "0" },
//       { id: 17, variant: "512GB SSD", price: "200" },
//       { id: 18, variant: "1TB SSD", price: "400" },
//     ],
//     cover: "/uploads/image_macbook_air_2023.png",
//     screenSize: "13.6",
//     cpu: "Apple M2",
//     cores: "8",
//     mainCamera: "N/A",
//     frontCamera: "1080p HD",
//     battery: "4379",
//     ram: "16",
//     slug: "macbook-air-2023",
//     colors: [
//       { id: 14, name: "#C0C0C0" },
//       { id: 15, name: "#000000" },
//       { id: 16, name: "#F5F5F5" },
//     ],
//   },
// ];

// export const ProductsInBulk = [
//   {
//     title: "Apple Watch Series 9",
//     price: "499.99",
//     stock: 50,
//     description:
//  "The Apple Watch Series 9 features a stunning Always-On Retina display and the new S9 chip for faster performance. It comes with advanced health and fitness tracking, including blood oxygen monitoring and ECG. The watch offers GPS, cellular connectivity, and a wide range of sensors. Available in multiple colors and finishes, it is perfect for both fitness enthusiasts and everyday users.",
//     categoryId: "71a89833-9e30-422b-9ad7-ba13920f2b8a",
//     brandId: "ee10611c-7282-47fc-a440-633400654cdc",
//     variants: [
//       { id: 1, variant: "40mm", price: "0" },
//       { id: 2, variant: "44mm", price: "50" },
//     ],
//     cover: "/uploads/image_apple_watch_series_9.png",
//     screenSize: "1.78",
//     screenType: "Retina",
//     battery: "284", // Battery capacity in mAh
//     cpu: "Apple S9", // Added CPU field
//     features: "Blood Oxygen Monitoring, ECG, Always-On Display",
//     connectivity: "GPS, Cellular, Wi-Fi, Bluetooth",
//     sensors: "Accelerometer, Gyroscope, Heart Rate Monitor",
//     slug: "apple-watch-series-9",
//     colors: [
//       { id: 1, name: "#F0F0F0" },
//       { id: 2, name: "#000000" },
//     ],
//   },
//   {
//     title: "Samsung Galaxy Watch 6",
//     price: "399.99",
//     stock: 40,
//     description:
//       "The Samsung Galaxy Watch 6 offers a sleek design and advanced features, including a Super AMOLED display, blood pressure monitoring, and sleep tracking. Powered by the Exynos W930 processor, it ensures smooth performance and long battery life. It supports GPS, LTE, and NFC, making it a versatile smartwatch for any lifestyle.",
//     categoryId: "71a89833-9e30-422b-9ad7-ba13920f2b8a",
//     brandId: "061ef0bc-8dbc-4691-a884-f1ce8dea17a6",
//     variants: [
//       { id: 3, variant: "40mm", price: "0" },
//       { id: 4, variant: "44mm", price: "50" },
//     ],
//     cover: "/uploads/image_samsung_galaxy_watch_6.png",
//     screenSize: "1.4",
//     screenType: "Super AMOLED",
//     battery: "361", // Battery capacity in mAh
//     cpu: "Exynos W930", // Added CPU field
//     features:
//       "Blood Pressure Monitoring, Sleep Tracking, Customizable Watch Faces",
//     connectivity: "GPS, LTE, Wi-Fi, Bluetooth, NFC",
//     sensors: "Accelerometer, Barometer, Gyroscope, Heart Rate Monitor",
//     slug: "samsung-galaxy-watch-6",
//     colors: [
//       { id: 3, name: "#1C1C1C" },
//       { id: 4, name: "#E5E5E5" },
//     ],
//   },
// {
//   title: "Google Pixel Watch",
//   price: "349.99",
//   stock: 60,
//   description:
//     "The Google Pixel Watch combines sleek design with powerful features. It runs on Wear OS and integrates seamlessly with Google services like Assistant and Maps. The Pixel Watch tracks heart rate, sleep, and more, with advanced sensors and a beautiful circular AMOLED display. It also supports Google Pay and offers excellent battery life.",
//   categoryId: "71a89833-9e30-422b-9ad7-ba13920f2b8a",
//   brandId: "1d6b0eb8-19fa-4116-b997-bfd4f8aa0955",
//   variants: [{ id: 5, variant: "41mm", price: "0" }],
//   cover: "/uploads/image_google_pixel_watch.png",
//   screenSize: "1.2",
//   screenType: "AMOLED",
//   battery: "294", // Battery capacity in mAh
//   cpu: "Exynos 9110", // Added CPU field
//   features: "Heart Rate Monitoring, Sleep Tracking, Google Pay",
//   connectivity: "GPS, Wi-Fi, Bluetooth, NFC",
//   sensors: "Accelerometer, Gyroscope, Optical Heart Rate Sensor",
//   slug: "google-pixel-watch",
//   colors: [
//     { id: 5, name: "#FFFFFF" },
//     { id: 6, name: "#000000" },
//   ],
// },
// {
//   title: "Xiaomi Watch S1 Pro",
//   price: "249.99",
//   stock: 70,
//   description:
//     "The Xiaomi Watch S1 Pro offers a premium build with sapphire glass and stainless steel frame. It comes with a 1.47-inch AMOLED display and includes advanced health tracking features like SpO2 monitoring and heart rate tracking. With a long battery life and comprehensive fitness tracking, it is a great companion for any activity.",
//   categoryId: "71a89833-9e30-422b-9ad7-ba13920f2b8a",
//   brandId: "28f37902-51d3-4734-9994-4edfe3a2e124",
//   variants: [{ id: 6, variant: "47mm", price: "0" }],
//   cover: "/uploads/image_xiaomi_watch_s1_pro.png",
//   screenSize: "1.47",
//   screenType: "AMOLED",
//   battery: "500", // Battery capacity in mAh
//   cpu: "Qualcomm Snapdragon Wear 4100+", // Added CPU field
//   features: "SpO2 Monitoring, Heart Rate Tracking, 5ATM Water Resistance",
//   connectivity: "GPS, Wi-Fi, Bluetooth",
//   sensors: "Accelerometer, Gyroscope, SpO2 Sensor",
//   slug: "xiaomi-watch-s1-pro",
//   colors: [
//     { id: 7, name: "#C0C0C0" },
//     { id: 8, name: "#1F1F1F" },
//   ],
// },
//];

// export const ProductsInBulk = [
//   {
//     title: "OnePlus 12",
//     price: "799.99",
//     stock: 30,
//     description:
//       "The OnePlus 12 is built for speed and power. Equipped with a 6.7-inch Fluid AMOLED display and a 120Hz refresh rate, it offers a seamless and vibrant viewing experience. Powered by the Snapdragon 8 Gen 3 processor and 12GB of RAM, it ensures smooth performance across all apps and games. Capture detailed photos with the 50MP main camera and 32MP front camera. With a 5000mAh battery and Warp Charge 100, it powers up in minutes. Available in Volcanic Black and Arctic Blue.",
//     categoryId: "71a89833-9e30-422b-9ad7-ba13920f2b8a",
//     brandId: "23937424-9f80-4b55-a703-cf9dbba82070",
//     variants: [
//       { id: 4, variant: "256GB", price: "0" },
//       { id: 5, variant: "512GB", price: "100" },
//     ],
//     cover: "/uploads/image_oneplus_12.png",
//     screenSize: "6.7",
//     cpu: "Snapdragon 8 Gen 3",
//     cores: "8",
//     mainCamera: "50MP",
//     frontCamera: "32MP",
//     battery: "5000",
//     ram: "12",
//     slug: "oneplus-12",
//     colors: [
//       { id: 3, name: "#1A1A1A" },
//       { id: 4, name: "#4A90E2" },
//     ],
//   },
// ];

//[
// {
//   title: "Samsung Galaxy S24",
//   price: "1099.99",
//   stock: 20,
//   description:
//     "Experience the future with the Samsung Galaxy S24. Featuring a 6.1-inch Dynamic AMOLED 2X display, it delivers vivid colors and deep blacks. Powered by the Exynos 2400/Snapdragon 8 Gen 3 processor and 12GB of RAM, it offers seamless performance. The 50MP triple camera system captures incredible detail, while the 12MP front camera is perfect for selfies. With a 4200mAh battery, it keeps you connected all day. Available in Phantom Black and Cream.",
//   categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//   brandId: "061ef0bc-8dbc-4691-a884-f1ce8dea17a6",
//   variants: [
//     { id: 6, variant: "128GB", price: "0" },
//     { id: 7, variant: "256GB", price: "100" },
//   ],
//   cover: "/uploads/image_galaxy_s24.png",
//   screenSize: "6.1",
//   cpu: "Snap 8 Gen 3",
//   cores: "8",
//   mainCamera: "50MP",
//   frontCamera: "12MP",
//   battery: "4200",
//   ram: "12",
//   slug: "samsung-galaxy-s24",
//   colors: [
//     { id: 5, name: "#000000" },
//     { id: 6, name: "#FFF5E1" },
//   ],
// },
// {
//   title: "Samsung Galaxy S24+",
//   price: "1199.99",
//   stock: 15,
//   description:
//     "The Samsung Galaxy S24+ brings all the power of the S24 with a larger 6.7-inch Dynamic AMOLED 2X display for an immersive viewing experience. Powered by the Exynos 2400/Snapdragon 8 Gen 3 processor and 12GB of RAM, it handles everything you throw at it. The 50MP triple camera system and 12MP front camera make it easy to capture stunning photos and videos. With a larger 4800mAh battery, it ensures all-day power. Available in Phantom Black and Ice Blue.",
//   categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//   brandId: "061ef0bc-8dbc-4691-a884-f1ce8dea17a6",
//   variants: [
//     { id: 8, variant: "256GB", price: "0" },
//     { id: 9, variant: "512GB", price: "150" },
//   ],
//   cover: "/uploads/image_galaxy_s24_plus.png",
//   screenSize: "6.7",
//   cpu: "Snap 8 Gen 3",
//   cores: "8",
//   mainCamera: "50MP",
//   frontCamera: "12MP",
//   battery: "4800",
//   ram: "12",
//   slug: "samsung-galaxy-s24-plus",
//   colors: [
//     { id: 7, name: "#000000" },
//     { id: 8, name: "#E0F7FA" },
//   ],
// },
// {
//   title: "iPhone 14",
//   price: "799.99",
//   stock: 35,
//   description:
//     "The iPhone 14 brings powerful performance and advanced features to your fingertips. With a 6.1-inch Super Retina XDR display, it offers vibrant colors and sharp details. Powered by the A15 Bionic chip and 6GB of RAM, the iPhone 14 delivers smooth performance in every app. Capture stunning photos and videos with the dual 12MP camera system, and enjoy longer battery life with its 3240mAh battery. Available in Midnight, Starlight, and Product(RED).",
//   categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//   brandId: "ee10611c-7282-47fc-a440-633400654cdc",
//   variants: [
//     { id: 10, variant: "128GB", price: "0" },
//     { id: 11, variant: "256GB", price: "100" },
//     { id: 12, variant: "512GB", price: "300" },
//   ],
//   cover: "/uploads/image_iphone_14.png",
//   screenSize: "6.1",
//   cpu: "A15 Bionic",
//   cores: "6",
//   mainCamera: "12MP",
//   frontCamera: "12MP",
//   battery: "3240",
//   ram: "6",
//   slug: "iphone-14",
//   colors: [
//     { id: 9, name: "#000000" },
//     { id: 10, name: "#F5F5F5" },
//     { id: 11, name: "#D00000" },
//   ],
// },
// {
//   title: "iPhone 14 Pro",
//   price: "999.99",
//   stock: 28,
//   description:
//     "The iPhone 14 Pro is the ultimate smartphone for those who demand the best. Featuring a 6.1-inch Super Retina XDR display with ProMotion technology, it offers smooth and responsive visuals. Powered by the A16 Bionic chip and 6GB of RAM, it handles the most demanding tasks with ease. The Pro camera system includes a 48MP main camera, 12MP ultra-wide camera, and 12MP telephoto camera, making it perfect for professional photography. With a 3095mAh battery, it provides all-day power. Available in Deep Purple, Gold, and Silver.",
//   categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//   brandId: "ee10611c-7282-47fc-a440-633400654cdc",
//   variants: [
//     { id: 13, variant: "128GB", price: "0" },
//     { id: 14, variant: "256GB", price: "100" },
//     { id: 15, variant: "512GB", price: "300" },
//   ],
//   cover: "/uploads/image_iphone_14_pro.png",
//   screenSize: "6.1",
//   cpu: "A16 Bionic",
//   cores: "6",
//   mainCamera: "48MP",
//   frontCamera: "12MP",
//   battery: "3095",
//   ram: "6",
//   slug: "iphone-14-pro",
//   colors: [
//     { id: 12, name: "#5D3FD3" },
//     { id: 13, name: "#FFD700" },
//     { id: 14, name: "#C0C0C0" },
//   ],
// },
// {
//   title: "iPad Pro 2024",
//   price: "999.99",
//   stock: 25,
//   description:
//     "The iPad Pro 2024 redefines what's possible with a tablet. Featuring a stunning 12.9-inch Liquid Retina XDR display, it delivers exceptional brightness and color accuracy for creatives and professionals. Powered by the M3 chip and 16GB of RAM, it handles the most demanding tasks with ease. Capture brilliant photos and videos with the 12MP Ultra Wide front camera and 12MP wide back camera. With support for the latest Apple Pencil and Magic Keyboard, it is perfect for drawing, note-taking, and productivity on the go. Available in Space Gray and Silver.",
//   categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//   brandId: "ee10611c-7282-47fc-a440-633400654cdc",
//   variants: [
//     { id: 1, variant: "128GB", price: "0" },
//     { id: 2, variant: "256GB", price: "150" },
//     { id: 3, variant: "512GB", price: "300" },
//   ],
//   cover: "/uploads/image_ipad_pro_2024.png",
//   screenSize: "12.9",
//   cpu: "M3",
//   cores: "8",
//   mainCamera: "12MP",
//   frontCamera: "12MP",
//   battery: "10000",
//   ram: "16",
//   slug: "ipad-pro-2024",
//   colors: [
//     { id: 1, name: "#A3A3A3" },
//     { id: 2, name: "#000000" },
//   ],
// },
//   {
//     title: "Samsung Galaxy S23 Ultra",
//     price: "1199.99",
//     stock: 20,
//     description:
//       "Experience the epitome of technological innovation with the Samsung Galaxy S23 Ultra. Boasting a stunning 6.8-inch display that dazzles with vibrant colors and deep contrasts, this flagship device redefines visual excellence. Powered by the Snapdragon 8 Gen 2 processor and 12GB of RAM, it delivers unparalleled performance, effortlessly handling multitasking and demanding apps. Capture every moment in extraordinary detail with its 108MP main camera and 40MP front camera. Equipped with a robust 5000mAh battery, the Galaxy S23 Ultra ensures lasting power throughout your day. Available in sophisticated shades including Midnight Black and Silver Titanium.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "061ef0bc-8dbc-4691-a884-f1ce8dea17a6",
//     variants: [
//       { id: 1, variant: "256GB", price: "0" },
//       { id: 2, variant: "512GB", price: "200" },
//     ],
//     cover: "/uploads/image_1678324825.png",
//     screenSize: "6.8",
//     cpu: "Snapdragon 8 Gen 2",
//     cores: "8",
//     mainCamera: "108MP",
//     frontCamera: "40MP",
//     battery: "5000",
//     slug: "samsung-galaxy-s23-ultra",
//     ram: "12",
//     colors: [
//       { id: 1, name: "#000000" },
//       { id: 2, name: "#C0C0C0" },
//     ],
//   },
//   {
//     title: "Google Pixel 7 Pro",
//     price: "899.99",
//     stock: 20,
//     description:
//       "Elevate your photography and performance with the Google Pixel 7 Pro. Featuring an exceptional 6.7-inch display, this smartphone delivers true-to-life colors and smooth visuals, perfect for streaming and gaming. Powered by the Google Tensor 2 processor and 12GB of RAM, it ensures seamless performance and efficiency. Capture breathtaking shots with its advanced 50MP main camera and 11.1MP front camera, designed to excel in low-light conditions. With a durable 5000mAh battery, the Pixel 7 Pro keeps up with your busy lifestyle. Choose from sophisticated colors like Charcoal Gray and Clearly White to match your style.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "1d6b0eb8-19fa-4116-b997-bfd4f8aa0955",
//     variants: [
//       { id: 5, variant: "128GB", price: "0" },
//       { id: 6, variant: "256GB", price: "100" },
//     ],
//     cover: "/uploads/image_167832333.png",
//     screenSize: "6.7",
//     cpu: "Google Tensor 2",
//     cores: "8",
//     mainCamera: "50MP",
//     frontCamera: "11.1MP",
//     battery: "5000",
//     ram: "12",
//     slug: "google-pixel-7-pro",
//     colors: [
//       { id: 5, name: "#333333" },
//       { id: 6, name: "#FFFFFF" },
//     ],
//   },
//   {
//     title: "OnePlus 11",
//     price: "799.99",
//     stock: 10,
//     description:
//       "Discover the OnePlus 11, a blend of high performance and sleek design. Its 6.55-inch display offers a smooth viewing experience with vibrant colors and clarity. Powered by the Snapdragon 8+ Gen 1 processor and 8GB of RAM, it delivers exceptional speed and responsiveness. Capture stunning photos with its 48MP main camera and 16MP front camera, perfect for capturing every detail. With a reliable 4500mAh battery, the OnePlus 11 keeps you connected throughout the day. Available in sleek colors such as Carbon Black and Aquamarine Green, it combines style with functionality.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "23937424-9f80-4b55-a703-cf9dbba82070  ",
//     variants: [
//       { id: 7, variant: "128GB", price: "0" },
//       { id: 8, variant: "256GB", price: "100" },
//     ],
//     cover: "/uploads/image_1718843579000.png",
//     screenSize: "6.55",
//     cpu: "Snapdragon 8+ Gen 1",
//     cores: "8",
//     mainCamera: "48MP",
//     frontCamera: "16MP",
//     battery: "4500",
//     ram: "8",
//     slug: "oneplus-11",
//     colors: [
//       { id: 7, name: "#1A1A1A" },
//       { id: 8, name: "#01796F" },
//     ],
//   },
//   {
//     title: "Xiaomi Mi 12",
//     price: "699.99",
//     stock: 15,
//     description:
//       "Experience excellence without compromise with the Xiaomi Mi 12. Featuring a compact 6.28-inch display, this smartphone delivers vivid colors and sharp details. Powered by the Snapdragon 8 Gen 1 processor and 8GB of RAM, it offers smooth performance for gaming and multitasking. Capture stunning photos with its 50MP main camera and crisp 20MP front camera, perfect for selfies and video calls. With a reliable 4500mAh battery, the Xiaomi Mi 12 keeps up with your active lifestyle. Available in classic colors like Onyx Black and Sapphire Blue to match your personal style.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "28f37902-51d3-4734-9994-4edfe3a2e124",
//     variants: [
//       { id: 9, variant: "128GB", price: "0" },
//       { id: 10, variant: "256GB", price: "100" },
//     ],
//     cover: "/uploads/image_1718843579090.png",
//     screenSize: "6.28",
//     cpu: "Snapdragon 8 Gen 1",
//     cores: "8",
//     mainCamera: "50MP",
//     frontCamera: "20MP",
//     battery: "4500",
//     ram: "8",
//     slug: "xiaomi-mi-12",
//     colors: [
//       { id: 9, name: "#000000" },
//       { id: 10, name: "#0000FF" },
//     ],
//   },
//   {
//     title: "Apple iPhone 15 Pro",
//     price: "1299.99",
//     stock: 20,
//     description:
//       "Enter a new era of innovation with the Apple iPhone 15 Pro. Boasting a stunning 6.9-inch Super Retina XDR display, this smartphone delivers breathtaking clarity and true-to-life colors. Powered by the cutting-edge Apple A16 Bionic chip and 8GB of RAM, it offers unparalleled performance and efficiency. Capture the world with its advanced 64MP main camera and 16MP front camera, optimized for professional-grade photography and cinematic videos. With a robust 4500mAh battery, the iPhone 15 Pro ensures all-day usage. Choose from elegant colors like Midnight Blue, Platinum Silver, Graphite Gray, and Pearl White to reflect your personal style.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "ee10611c-7282-47fc-a440-633400654cdc",
//     variants: [
//       { id: 11, variant: "256GB", price: "0" },
//       { id: 12, variant: "512GB", price: "200" },
//     ],
//     cover: "/uploads/image_1718843579040.png",
//     screenSize: "6.9",
//     cpu: "Apple A16 Bionic",
//     cores: "8",
//     mainCamera: "64MP",
//     frontCamera: "16MP",
//     battery: "4500",
//     ram: "8",
//     slug: "apple-iphone-15-pro",
//     colors: [
//       { id: 88, name: "#3B4E7E" },
//       { id: 89, name: "#C0C0C0" },
//       { id: 99, name: "#333333" },
//       { id: 100, name: "#F0F0F0" },
//     ],
//   },
//   {
//     title: "Sony Xperia 5 IV",
//     price: "999.99",
//     stock: 15,
//     description:
//       "Unleash your creativity with the Sony Xperia 5 IV. Featuring a sleek 6.1-inch CinemaWide OLED display, this smartphone offers immersive viewing experiences with vibrant colors and deep blacks. Powered by the Snapdragon 8 Gen 2 processor and 6GB of RAM, it provides exceptional performance for gaming and productivity. Capture stunning photos with its versatile 48MP main camera and high-resolution 12MP front camera, ideal for capturing detailed shots and selfies. With a 4000mAh battery, the Xperia 5 IV ensures long-lasting usage. Available in timeless colors like Midnight Black and Lunar Gray to suit your individual taste.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "061ef0bc-8dbc-4691-a884-f1ce8dea17a6",
//     variants: [
//       { id: 13, variant: "128GB", price: "0" },
//       { id: 14, variant: "256GB", price: "100" },
//     ],
//     cover: "/uploads/image_xperia_5_iv.png",
//     screenSize: "6.1",
//     cpu: "Snapdragon 8 Gen 2",
//     cores: "8",
//     mainCamera: "48MP",
//     frontCamera: "12MP",
//     battery: "4000",
//     ram: "6",
//     slug: "sony-xperia-5-iv",
//     colors: [
//       { id: 13, name: "#000000" },
//       { id: 14, name: "#8C8C8C" },
//     ],
//   },
//   {
//     title: "Samsung Galaxy Z Fold 5",
//     price: "1799.99",
//     stock: 15,
//     description:
//       "Redesign your smartphone experience with the Samsung Galaxy Z Fold 5. Featuring a revolutionary foldable 7.2-inch Dynamic AMOLED display, this device combines the portability of a smartphone with the multitasking capabilities of a tablet. Powered by the Snapdragon 8 Gen 2 processor and 12GB of RAM, it delivers powerful performance for seamless multitasking and gaming. Capture stunning details with its 108MP main camera and 40MP front camera, perfect for capturing high-resolution photos and videos. With a versatile 4400mAh battery, the Galaxy Z Fold 5 keeps you connected throughout the day. Available in timeless colors like Phantom Black and Mystic White to complement your style.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "",
//     variants: [
//       { id: 15, variant: "256GB", price: "0" },
//       { id: 16, variant: "512GB", price: "200" },
//     ],
//     cover: "/uploads/galaxy_z_fold_5.png",
//     screenSize: "7.2",
//     cpu: "Snapdragon 8 Gen 2",
//     cores: "8",
//     mainCamera: "108MP",
//     frontCamera: "40MP",
//     battery: "4400",
//     ram: "12",
//     slug: "samsung-galaxy-z-fold-5",
//     colors: [
//       { id: 15, name: "#000000" },
//       { id: 16, name: "#FFFFFF" },
//     ],
//   },
//   {
//     title: "Xiaomi Redmi Note 12 Pro",
//     price: "399.99",
//     stock: 25,
//     description:
//       "Discover the Xiaomi Redmi Note 12 Pro, designed for those who seek a large display and exceptional battery life. Featuring a spacious 6.8-inch screen, this smartphone offers immersive visuals for gaming and multimedia. Powered by the Snapdragon 7 Gen 1 processor and 8GB of RAM, it ensures smooth performance and responsiveness. Capture detailed photos with its advanced 64MP main camera and high-resolution 32MP front camera, perfect for photography enthusiasts. With a robust 5000mAh battery, the Redmi Note 12 Pro keeps you connected throughout the day. Choose from vibrant colors like Ocean Blue and Crimson Red to suit your style.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "28f37902-51d3-4734-9994-4edfe3a2e124",
//     variants: [
//       { id: 17, variant: "128GB", price: "0" },
//       { id: 18, variant: "256GB", price: "50" },
//     ],
//     cover: "/uploads/redmi_note_12_pro.png",
//     screenSize: "6.8",
//     cpu: "Snapdragon 7 Gen 1",
//     cores: "8",
//     mainCamera: "64MP",
//     frontCamera: "32MP",
//     battery: "5000",
//     ram: "8",
//     slug: "xiaomi-redmi-note-12-pro",
//     colors: [
//       { id: 17, name: "#0000FF" },
//       { id: 18, name: "#c83131" },
//     ],
//   },
//   {
//     title: "OnePlus Nord 3",
//     price: "599.99",
//     stock: 20,
//     description:
//       "Experience speed and superior camera performance with the OnePlus Nord 3. Featuring a sleek 6.6-inch display, this smartphone offers vibrant visuals and smooth touch response. Powered by the Snapdragon 870 processor and 12GB of RAM, it delivers lightning-fast performance for gaming and multitasking. Capture stunning photos with its 50MP main camera and high-resolution 32MP front camera, designed to capture every detail. With a 4500mAh battery, the Nord 3 ensures lasting power for your daily activities. Available in stylish colors like Stealth Black and Horizon Blue to match your personal style.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "23937424-9f80-4b55-a703-cf9dbba82070",
//     variants: [
//       { id: 19, variant: "128GB", price: "0" },
//       { id: 20, variant: "256GB", price: "200" },
//     ],
//     cover: "/uploads/nord3.png",
//     screenSize: "6.6",
//     cpu: "Snapdragon 870",
//     cores: "8",
//     mainCamera: "50MP",
//     frontCamera: "32MP",
//     battery: "4500",
//     ram: "12",
//     slug: "oneplus-nord-3",
//     colors: [
//       { id: 19, name: "#1A1A1A" },
//       { id: 20, name: "#01796F" },
//     ],
//   },
//   {
//     title: "Apple iPhone SE (2024)",
//     price: "699.99",
//     stock: 15,
//     description:
//       "Introducing the compact yet powerful Apple iPhone SE (2024), designed to deliver exceptional performance in a pocket-friendly design. Featuring a 4.7-inch Retina HD display, this iPhone is perfect for one-handed use and fits comfortably in your hand. Powered by the advanced A16 Bionic chip and 4GB of RAM, it offers smooth performance for everyday tasks and gaming. Capture sharp and vibrant photos with its 12MP main camera and 7MP front camera, ideal for capturing memorable moments. With a reliable 2400mAh battery, the iPhone SE (2024) ensures all-day usage. Available in classic colors like Space Gray, Silver, and Product(Red) to match your personal style.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "ee10611c-7282-47fc-a440-633400654cdc",
//     variants: [
//       { id: 21, variant: "128GB", price: "0" },
//       { id: 22, variant: "256GB", price: "100" },
//     ],
//     cover: "/uploads/iphone_se.png",
//     screenSize: "4.7",
//     cpu: "Apple A16 Bionic",
//     cores: "6",
//     mainCamera: "12MP",
//     frontCamera: "7MP",
//     battery: "2400",
//     ram: "4",
//     slug: "apple-iphone-se-2024",
//     colors: [
//       { id: 21, name: "#000000" },
//       { id: 22, name: "#FFFFFF" },
//       { id: 222, name: "#c83131" },
//     ],
//   },
//   {
//     title: "Sony Xperia 1 III",
//     price: "1099.99",
//     stock: 18,
//     description:
//       "Unleash your creativity with the Sony Xperia 1 III, a smartphone designed for professional photographers and multimedia enthusiasts. Featuring a stunning 6.5-inch 4K HDR OLED display, this Xperia model delivers exceptional clarity and color accuracy. Powered by the Snapdragon 888 processor and 12GB of RAM, it offers powerful performance for multitasking and gaming. Capture stunning photos with its versatile 12MP main camera and 8MP front camera, equipped with professional-grade features like Real-time Eye AF and 20fps continuous shooting. With a 4500mAh battery, the Xperia 1 III ensures long-lasting usage. Available in stylish colors like Black and Frosted Purple to complement your creative lifestyle.",
//     categoryId: "bdd821cf-871b-401d-ae7a-3dd8ce2d7fe2",
//     brandId: "061ef0bc-8dbc-4691-a884-f1ce8dea17a6",
//     variants: [
//       { id: 23, variant: "256GB", price: "0" },
//       { id: 24, variant: "512GB", price: "200" },
//     ],
//     cover: "/uploads/image_xperia_1_iii.png",
//     screenSize: "6.5",
//     cpu: "Snapdragon 888",
//     cores: "8",
//     mainCamera: "12MP",
//     frontCamera: "8MP",
//     battery: "4500",
//     ram: "12",
//     slug: "sony-xperia-1-iii",
//     colors: [
//       { id: 23, name: "#000000" },
//       { id: 24, name: "#8C8C8C" },
//     ],
//   },
// ];
