export const ProductsInBulk = [
  {
    title: "Samsung Galaxy S23 Ultra",
    price: "1199.99",
    stock: 20,
    description:
      "Experience the epitome of technological innovation with the Samsung Galaxy S23 Ultra. Boasting a stunning 6.8-inch display that dazzles with vibrant colors and deep contrasts, this flagship device redefines visual excellence. Powered by the Snapdragon 8 Gen 2 processor and 12GB of RAM, it delivers unparalleled performance, effortlessly handling multitasking and demanding apps. Capture every moment in extraordinary detail with its 108MP main camera and 40MP front camera. Equipped with a robust 5000mAh battery, the Galaxy S23 Ultra ensures lasting power throughout your day. Available in sophisticated shades including Midnight Black and Silver Titanium.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "3befceb3-e925-4be3-91ec-9efae283871f",
    variants: [
      { id: 1, name: "256GB", price: 0 },
      { id: 2, name: "512GB", price: 200 },
    ],
    cover: "/uploads/image_1678324825.jpg",
    screenSize: "6.8",
    cpu: "Snapdragon 8 Gen 2",
    cores: "8",
    mainCamera: "108MP",
    frontCamera: "40MP",
    battery: "5000",
    ram: "12",
    colors: [
      { id: 1, name: "#000000" },
      { id: 2, name: "#C0C0C0" },
    ],
  },
  {
    title: "Google Pixel 7 Pro",
    price: "899.99",
    stock: 20,
    description:
      "Elevate your photography and performance with the Google Pixel 7 Pro. Featuring an exceptional 6.7-inch display, this smartphone delivers true-to-life colors and smooth visuals, perfect for streaming and gaming. Powered by the Google Tensor 2 processor and 12GB of RAM, it ensures seamless performance and efficiency. Capture breathtaking shots with its advanced 50MP main camera and 11.1MP front camera, designed to excel in low-light conditions. With a durable 5000mAh battery, the Pixel 7 Pro keeps up with your busy lifestyle. Choose from sophisticated colors like Charcoal Gray and Clearly White to match your style.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "ef6bc2aa-feb5-43d7-9c5c-bd12a9f568ae",
    variants: [
      { id: 5, name: "128GB", price: 0 },
      { id: 6, name: "256GB", price: 100 },
    ],
    cover: "/uploads/image_167832333.jpg",
    screenSize: "6.7",
    cpu: "Google Tensor 2",
    cores: "8",
    mainCamera: "50MP",
    frontCamera: "11.1MP",
    battery: "5000",
    ram: "12",
    colors: [
      { id: 5, name: "#333333" },
      { id: 6, name: "#FFFFFF" },
    ],
  },
  {
    title: "OnePlus 11",
    price: "799.99",
    stock: 10,
    description:
      "Discover the OnePlus 11, a blend of high performance and sleek design. Its 6.55-inch display offers a smooth viewing experience with vibrant colors and clarity. Powered by the Snapdragon 8+ Gen 1 processor and 8GB of RAM, it delivers exceptional speed and responsiveness. Capture stunning photos with its 48MP main camera and 16MP front camera, perfect for capturing every detail. With a reliable 4500mAh battery, the OnePlus 11 keeps you connected throughout the day. Available in sleek colors such as Carbon Black and Aquamarine Green, it combines style with functionality.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "e8010c42-2389-4bdc-a7dc-300b8e9292d7",
    variants: [
      { id: 7, name: "128GB", price: 0 },
      { id: 8, name: "256GB", price: 100 },
    ],
    cover: "/uploads/image_1718843579000.png",
    screenSize: "6.55",
    cpu: "Snapdragon 8+ Gen 1",
    cores: "8",
    mainCamera: "48MP",
    frontCamera: "16MP",
    battery: "4500",
    ram: "8",
    colors: [
      { id: 7, name: "#1A1A1A" },
      { id: 8, name: "#01796F" },
    ],
  },
  {
    title: "Xiaomi Mi 12",
    price: "699.99",
    stock: 15,
    description:
      "Experience excellence without compromise with the Xiaomi Mi 12. Featuring a compact 6.28-inch display, this smartphone delivers vivid colors and sharp details. Powered by the Snapdragon 8 Gen 1 processor and 8GB of RAM, it offers smooth performance for gaming and multitasking. Capture stunning photos with its 50MP main camera and crisp 20MP front camera, perfect for selfies and video calls. With a reliable 4500mAh battery, the Xiaomi Mi 12 keeps up with your active lifestyle. Available in classic colors like Onyx Black and Sapphire Blue to match your personal style.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "a92752c0-0aa6-496c-9c98-642f3452c4de",
    variants: [
      { id: 9, name: "128GB", price: 0 },
      { id: 10, name: "256GB", price: 100 },
    ],
    cover: "/uploads/image_1718843579090.png",
    screenSize: "6.28",
    cpu: "Snapdragon 8 Gen 1",
    cores: "8",
    mainCamera: "50MP",
    frontCamera: "20MP",
    battery: "4500",
    ram: "8",
    colors: [
      { id: 9, name: "#000000" },
      { id: 10, name: "#0000FF" },
    ],
  },
  {
    title: "Apple iPhone 15 Pro",
    price: "1299.99",
    stock: 20,
    description:
      "Enter a new era of innovation with the Apple iPhone 15 Pro. Boasting a stunning 6.9-inch Super Retina XDR display, this smartphone delivers breathtaking clarity and true-to-life colors. Powered by the cutting-edge Apple A16 Bionic chip and 8GB of RAM, it offers unparalleled performance and efficiency. Capture the world with its advanced 64MP main camera and 16MP front camera, optimized for professional-grade photography and cinematic videos. With a robust 4500mAh battery, the iPhone 15 Pro ensures all-day usage. Choose from elegant colors like Midnight Blue, Platinum Silver, Graphite Gray, and Pearl White to reflect your personal style.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "6b1f434f-6b10-4d7f-af5e-3206e5e2750d",
    variants: [
      { id: 11, name: "256GB", price: 0 },
      { id: 12, name: "512GB", price: 200 },
    ],
    cover: "/uploads/image_iphone_15_pro.jpg",
    screenSize: "6.9",
    cpu: "Apple A16 Bionic",
    cores: "8",
    mainCamera: "64MP",
    frontCamera: "16MP",
    battery: "4500",
    ram: "8",
    colors: [
      { id: 88, name: "#3B4E7E" },
      { id: 89, name: "#C0C0C0" },
      { id: 99, name: "#333333" },
      { id: 100, name: "#F0F0F0" },
    ],
  },
  {
    title: "Sony Xperia 5 IV",
    price: "999.99",
    stock: 15,
    description:
      "Unleash your creativity with the Sony Xperia 5 IV. Featuring a sleek 6.1-inch CinemaWide OLED display, this smartphone offers immersive viewing experiences with vibrant colors and deep blacks. Powered by the Snapdragon 8 Gen 2 processor and 6GB of RAM, it provides exceptional performance for gaming and productivity. Capture stunning photos with its versatile 48MP main camera and high-resolution 12MP front camera, ideal for capturing detailed shots and selfies. With a 4000mAh battery, the Xperia 5 IV ensures long-lasting usage. Available in timeless colors like Midnight Black and Lunar Gray to suit your individual taste.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "f02fb0f0-d76b-4338-a15a-56c23c8d8d58",
    variants: [
      { id: 13, name: "128GB", price: 0 },
      { id: 14, name: "256GB", price: 100 },
    ],
    cover: "/uploads/image_xperia_5_iv.jpg",
    screenSize: "6.1",
    cpu: "Snapdragon 8 Gen 2",
    cores: "8",
    mainCamera: "48MP",
    frontCamera: "12MP",
    battery: "4000",
    ram: "6",
    colors: [
      { id: 13, name: "#000000" },
      { id: 14, name: "#8C8C8C" },
    ],
  },
  {
    title: "Samsung Galaxy Z Fold 5",
    price: "1799.99",
    stock: 15,
    description:
      "Redesign your smartphone experience with the Samsung Galaxy Z Fold 5. Featuring a revolutionary foldable 7.2-inch Dynamic AMOLED display, this device combines the portability of a smartphone with the multitasking capabilities of a tablet. Powered by the Snapdragon 8 Gen 2 processor and 12GB of RAM, it delivers powerful performance for seamless multitasking and gaming. Capture stunning details with its 108MP main camera and 40MP front camera, perfect for capturing high-resolution photos and videos. With a versatile 4400mAh battery, the Galaxy Z Fold 5 keeps you connected throughout the day. Available in timeless colors like Phantom Black and Mystic White to complement your style.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "3befceb3-e925-4be3-91ec-9efae283871f",
    variants: [
      { id: 15, name: "256GB", price: 0 },
      { id: 16, name: "512GB", price: 200 },
    ],
    cover: "/uploads/image_galaxy_z_fold_5.jpg",
    screenSize: "7.2",
    cpu: "Snapdragon 8 Gen 2",
    cores: "8",
    mainCamera: "108MP",
    frontCamera: "40MP",
    battery: "4400",
    ram: "12",
    colors: [
      { id: 15, name: "#000000" },
      { id: 16, name: "#FFFFFF" },
    ],
  },
  {
    title: "Xiaomi Redmi Note 12 Pro",
    price: "399.99",
    stock: 25,
    description:
      "Discover the Xiaomi Redmi Note 12 Pro, designed for those who seek a large display and exceptional battery life. Featuring a spacious 6.8-inch screen, this smartphone offers immersive visuals for gaming and multimedia. Powered by the Snapdragon 7 Gen 1 processor and 8GB of RAM, it ensures smooth performance and responsiveness. Capture detailed photos with its advanced 64MP main camera and high-resolution 32MP front camera, perfect for photography enthusiasts. With a robust 5000mAh battery, the Redmi Note 12 Pro keeps you connected throughout the day. Choose from vibrant colors like Ocean Blue and Crimson Red to suit your style.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "a92752c0-0aa6-496c-9c98-642f3452c4de",
    variants: [
      { id: 17, name: "128GB", price: 0 },
      { id: 18, name: "256GB", price: 50 },
    ],
    cover: "/uploads/image_redmi_note_12_pro.jpg",
    screenSize: "6.8",
    cpu: "Snapdragon 7 Gen 1",
    cores: "8",
    mainCamera: "64MP",
    frontCamera: "32MP",
    battery: "5000",
    ram: "8",
    colors: [
      { id: 17, name: "#0000FF" },
      { id: 18, name: "#c83131" },
    ],
  },
  {
    title: "OnePlus Nord 3",
    price: "599.99",
    stock: 20,
    description:
      "Experience speed and superior camera performance with the OnePlus Nord 3. Featuring a sleek 6.6-inch display, this smartphone offers vibrant visuals and smooth touch response. Powered by the Snapdragon 870 processor and 12GB of RAM, it delivers lightning-fast performance for gaming and multitasking. Capture stunning photos with its 50MP main camera and high-resolution 32MP front camera, designed to capture every detail. With a 4500mAh battery, the Nord 3 ensures lasting power for your daily activities. Available in stylish colors like Stealth Black and Horizon Blue to match your personal style.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "e8010c42-2389-4bdc-a7dc-300b8e9292d7",
    variants: [
      { id: 19, name: "128GB", price: 0 },
      { id: 20, name: "256GB", price: 50 },
    ],
    cover: "/uploads/image_oneplus_nord_3.jpg",
    screenSize: "6.6",
    cpu: "Snapdragon 870",
    cores: "8",
    mainCamera: "50MP",
    frontCamera: "32MP",
    battery: "4500",
    ram: "12",
    colors: [
      { id: 19, name: "#1A1A1A" },
      { id: 20, name: "#01796F" },
    ],
  },
  {
    title: "Apple iPhone SE (2024)",
    price: "699.99",
    stock: 15,
    description:
      "Introducing the compact yet powerful Apple iPhone SE (2024), designed to deliver exceptional performance in a pocket-friendly design. Featuring a 4.7-inch Retina HD display, this iPhone is perfect for one-handed use and fits comfortably in your hand. Powered by the advanced A16 Bionic chip and 4GB of RAM, it offers smooth performance for everyday tasks and gaming. Capture sharp and vibrant photos with its 12MP main camera and 7MP front camera, ideal for capturing memorable moments. With a reliable 2400mAh battery, the iPhone SE (2024) ensures all-day usage. Available in classic colors like Space Gray, Silver, and Product(Red) to match your personal style.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "6b1f434f-6b10-4d7f-af5e-3206e5e2750d",
    variants: [
      { id: 21, name: "128GB", price: 0 },
      { id: 22, name: "256GB", price: 100 },
    ],
    cover: "/uploads/image_iphone_se_2024.jpg",
    screenSize: "4.7",
    cpu: "Apple A16 Bionic",
    cores: "6",
    mainCamera: "12MP",
    frontCamera: "7MP",
    battery: "2400",
    ram: "4",
    colors: [
      { id: 21, name: "#000000" },
      { id: 22, name: "#FFFFFF" },
      { id: 222, name: "#c83131" },
    ],
  },
  {
    title: "Sony Xperia 1 III",
    price: "1099.99",
    stock: 18,
    description:
      "Unleash your creativity with the Sony Xperia 1 III, a smartphone designed for professional photographers and multimedia enthusiasts. Featuring a stunning 6.5-inch 4K HDR OLED display, this Xperia model delivers exceptional clarity and color accuracy. Powered by the Snapdragon 888 processor and 12GB of RAM, it offers powerful performance for multitasking and gaming. Capture stunning photos with its versatile 12MP main camera and 8MP front camera, equipped with professional-grade features like Real-time Eye AF and 20fps continuous shooting. With a 4500mAh battery, the Xperia 1 III ensures long-lasting usage. Available in stylish colors like Black and Frosted Purple to complement your creative lifestyle.",
    categoryId: "ceb5ce6d-43b7-4466-ab64-317e0eb4de55",
    brandId: "f02fb0f0-d76b-4338-a15a-56c23c8d8d58",
    variants: [
      { id: 23, name: "256GB", price: 0 },
      { id: 24, name: "512GB", price: 200 },
    ],
    cover: "/uploads/image_xperia_1_iii.jpg",
    screenSize: "6.5",
    cpu: "Snapdragon 888",
    cores: "8",
    mainCamera: "12MP",
    frontCamera: "8MP",
    battery: "4500",
    ram: "12",
    colors: [
      { id: 23, name: "#000000" },
      { id: 24, name: "#8C8C8C" },
    ],
  },
];
