export const categoryFields = {
  Laptops: [
    {
      name: "screenSize",
      label: "Screen Size",
      type: "input",
      placeholder: "e.g., 15.6 inches",
    },
    {
      name: "cpu",
      label: "CPU",
      type: "input",
      placeholder: "e.g., Intel Core i7",
    },
    {
      name: "cores",
      label: "Cores",
      type: "input",
      placeholder: "e.g., Quad-core",
    },

    {
      name: "frontCamera",
      label: "Front Camera",
      type: "input",
      placeholder: "e.g., 5 MP",
    },
    { name: "ram", label: "RAM", type: "input", placeholder: "e.g., 16 GB" },
    {
      name: "battery",
      label: "Battery",
      type: "input",
      placeholder: "e.g., 4500",
    },
  ],
  Smartphones: [
    {
      name: "screenSize",
      label: "Screen Size",
      type: "input",
      placeholder: "e.g., 6.5 inches",
    },
    {
      name: "cpu",
      label: "CPU",
      type: "input",
      placeholder: "e.g., Snapdragon 888",
    },
    {
      name: "cores",
      label: "Cores",
      type: "input",
      placeholder: "e.g., Octa-core",
    },
    {
      name: "mainCamera",
      label: "Main Camera",
      type: "input",
      placeholder: "e.g., 48 MP",
    },
    {
      name: "frontCamera",
      label: "Front Camera",
      type: "input",
      placeholder: "e.g., 12 MP",
    },
    { name: "ram", label: "RAM", type: "input", placeholder: "e.g., 8 GB" },
    {
      name: "battery",
      label: "Battery",
      type: "input",
      placeholder: "e.g., 4500",
    },
  ],
  Smartwatches: [
    {
      name: "screenSize",
      label: "Screen Size",
      type: "input",
      placeholder: "e.g., 1.4 inches",
    },
    {
      name: "cpu",
      label: "CPU",
      type: "input",
      placeholder: "e.g., Exynos 9110",
    },
    {
      name: "sensor",
      label: "Sensors",
      type: "input",
      placeholder: "e.g., Heart Rate, GPS",
    },
    {
      name: "screenType",
      label: "Screen Type",
      type: "input",
      placeholder: "e.g., AMOLED",
    },
    {
      name: "connectivity",
      label: "Connectivity",
      type: "input",
      placeholder: "e.g., Bluetooth, Wi-Fi",
    },
    {
      name: "battery",
      label: "Battery",
      type: "input",
      placeholder: "e.g., 4500",
    },
    {
      name: "features",
      label: "Features",
      type: "input",
      placeholder: "e.g., Sleep Tracking, NFC",
    },
  ],
  Headphones: [
    {
      name: "sensor",
      label: "Sensors",
      type: "input",
      placeholder: "e.g., Proximity, Touch",
    },
    {
      name: "type",
      label: "Type",
      type: "input",
      placeholder: "e.g., Over-ear, In-ear",
    },
    {
      name: "battery",
      label: "Battery",
      type: "input",
      placeholder: "e.g., 4500",
    },
    {
      name: "batteryLife",
      label: "Battery Life",
      type: "input",
      placeholder: "e.g., 30 hours",
    },
    {
      name: "features",
      label: "Features",
      type: "input",
      placeholder: "e.g., Active Noise Cancellation",
    },
    { name: "microphone", label: "Microphone", type: "checkbox" },
    {
      name: "noiseCancellation",
      label: "Noise Cancellation",
      type: "checkbox",
    },
    { name: "wireless", label: "Wireless", type: "checkbox" },
  ],
  Cameras: [
    {
      name: "lens",
      label: "Camera Lens",
      type: "input",
      placeholder: "e.g., 24-70mm f/2.8",
    },
    {
      name: "maxResolution",
      label: "Max Resolution",
      type: "input",
      placeholder: "e.g., 4K UHD",
    },
    {
      name: "aperture",
      label: "Aperture",
      type: "input",
      placeholder: "e.g., f/2.8",
    },
    {
      name: "videoResolution",
      label: "Video Resolution",
      type: "input",
      placeholder: "e.g., 1080p",
    },
    {
      name: "zoom",
      label: "Zoom",
      type: "input",
      placeholder: "e.g., 10x Optical Zoom",
    },
    {
      name: "megapixels",
      label: "Megapixels",
      type: "input",
      placeholder: "e.g., 20 MP",
    },
    {
      name: "features",
      label: "Features",
      type: "input",
      placeholder: "e.g., Night Mode",
    },
  ],
  Gaming: [
    {
      name: "screenSize",
      label: "Screen Size",
      type: "input",
      placeholder: "e.g., 1.4 inches",
    },
    {
      name: "features",
      label: "Features",
      type: "input",
      placeholder: "e.g., Active Noise Cancellation",
    },
    {
      name: "screenType",
      label: "Screen Type",
      type: "input",
      placeholder: "e.g., AMOLED",
    },
    {
      name: "storage",
      label: "Storage",
      type: "input",
      placeholder: "e.g., 512GB",
    },
    {
      name: "cpu",
      label: "CPU",
      type: "input",
      placeholder: "e.g., Intel Core i7",
    },
    {
      name: "cores",
      label: "Cores",
      type: "input",
      placeholder: "e.g., Quad-core",
    },
    {
      name: "gpu",
      label: "GPU",
      type: "input",
      placeholder: "e.g., NVIDIA GeForce RTX 3080",
    },
    {
      name: "maxResolution",
      label: "Max Resolution",
      type: "input",
      placeholder: "e.g., 4K UHD",
    },
    {
      name: "numberOfControllers",
      label: "Number of Controllers",
      type: "input",
      placeholder: "e.g., 2",
    },
    {
      name: "compatibleGames",
      label: "Compatible Games",
      type: "input",
      placeholder: "e.g., Call of Duty, FIFA",
    },
  ],
};
